/********************************************************************************
** Form generated from reading ui file 'qgisapp.ui'
**
** Created: Tue Mar 13 10:24:14 2012
**      by: Qt User Interface Compiler version 4.5.3
**
** WARNING! All changes made in this file will be lost when recompiling ui file!
********************************************************************************/

#ifndef UI_QGISAPP_H
#define UI_QGISAPP_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QStatusBar>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *mActionNewProject;
    QAction *mActionOpenProject;
    QAction *mActionSaveProject;
    QAction *mActionSaveProjectAs;
    QAction *mActionSaveMapAsImage;
    QAction *mActionNewPrintComposer;
    QAction *mActionShowComposerManager;
    QAction *mActionExit;
    QAction *mActionUndo;
    QAction *mActionRedo;
    QAction *mActionCutFeatures;
    QAction *mActionCopyFeatures;
    QAction *mActionPasteFeatures;
    QAction *mActionCapturePoint;
    QAction *mActionCaptureLine;
    QAction *mActionCapturePolygon;
    QAction *mActionMoveFeature;
    QAction *mActionReshapeFeatures;
    QAction *mActionSplitFeatures;
    QAction *mActionDeleteSelected;
    QAction *mActionAddRing;
    QAction *mActionAddIsland;
    QAction *mActionSimplifyFeature;
    QAction *mActionDeleteRing;
    QAction *mActionDeletePart;
    QAction *mActionMergeFeatures;
    QAction *mActionMergeFeatureAttributes;
    QAction *mActionNodeTool;
    QAction *mActionRotatePointSymbols;
    QAction *mActionSnappingOptions;
    QAction *mActionPan;
    QAction *mActionZoomIn;
    QAction *mActionZoomOut;
    QAction *mActionSelect;
    QAction *mActionSelectRectangle;
    QAction *mActionSelectPolygon;
    QAction *mActionSelectFreehand;
    QAction *mActionSelectRadius;
    QAction *mActionDeselectAll;
    QAction *mActionIdentify;
    QAction *mActionMeasure;
    QAction *mActionMeasureArea;
    QAction *mActionMeasureAngle;
    QAction *mActionZoomFullExtent;
    QAction *mActionZoomToLayer;
    QAction *mActionZoomToSelected;
    QAction *mActionZoomLast;
    QAction *mActionZoomNext;
    QAction *mActionZoomActualSize;
    QAction *mActionMapTips;
    QAction *mActionNewBookmark;
    QAction *mActionShowBookmarks;
    QAction *mActionDraw;
    QAction *mActionTextAnnotation;
    QAction *mActionFormAnnotation;
    QAction *mActionAnnotation;
    QAction *mActionLabeling;
    QAction *mActionNewVectorLayer;
    QAction *mActionNewSpatialiteLayer;
    QAction *mActionShowRasterCalculator;
    QAction *mActionAddOgrLayer;
    QAction *mActionAddRasterLayer;
    QAction *mActionAddPgLayer;
    QAction *mActionAddSpatiaLiteLayer;
    QAction *mActionAddWmsLayer;
    QAction *mActionOpenTable;
    QAction *mActionToggleEditing;
    QAction *mActionSaveEdits;
    QAction *mActionLayerSaveAs;
    QAction *mActionLayerSelectionSaveAs;
    QAction *mActionRemoveLayer;
    QAction *mActionSetLayerCRS;
    QAction *mActionSetProjectCRSFromLayer;
    QAction *mActionTileScale;
    QAction *mActionGpsTool;
    QAction *mActionLayerProperties;
    QAction *mActionLayerSubsetString;
    QAction *mActionAddToOverview;
    QAction *mActionAddAllToOverview;
    QAction *mActionRemoveAllFromOverview;
    QAction *mActionShowAllLayers;
    QAction *mActionHideAllLayers;
    QAction *mActionManagePlugins;
    QAction *mActionToggleFullScreen;
    QAction *mActionProjectProperties;
    QAction *mActionOptions;
    QAction *mActionCustomProjection;
    QAction *mActionConfigureShortcuts;
    QAction *mActionLocalHistogramStretch;
    QAction *mActionHelpContents;
    QAction *mActionHelpAPI;
    QAction *mActionQgisHomePage;
    QAction *mActionCheckQgisVersion;
    QAction *mActionAbout;
    QAction *mActionSponsors;
    QAction *mActionMoveLabel;
    QAction *mActionRotateLabel;
    QAction *mActionChangeLabelProperties;
    QAction *mActionStyleManagerV2;
    QAction *mActionShowPythonDialog;
    QAction *mActionFullHistogramStretch;
    QAction *mActionAddLayerSeparator;
    QWidget *centralwidget;
    QMenuBar *menubar;
    QMenu *mEditMenu;
    QMenu *mFileMenu;
    QMenu *mRecentProjectsMenu;
    QMenu *mPrintComposersMenu;
    QMenu *mViewMenu;
    QMenu *menuSelect;
    QMenu *menuMeasure;
    QMenu *mLayerMenu;
    QMenu *menuNew;
    QMenu *mSettingsMenu;
    QMenu *mPluginMenu;
    QMenu *mRasterMenu;
    QMenu *mHelpMenu;
    QStatusBar *statusbar;
    QToolBar *mFileToolBar;
    QToolBar *mLayerToolBar;
    QToolBar *mDigitizeToolBar;
    QToolBar *mAdvancedDigitizeToolBar;
    QToolBar *mMapNavToolBar;
    QToolBar *mAttributesToolBar;
    QToolBar *mPluginToolBar;
    QToolBar *mHelpToolBar;
    QToolBar *mRasterToolBar;
    QToolBar *mLabelToolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1054, 491);
        mActionNewProject = new QAction(MainWindow);
        mActionNewProject->setObjectName(QString::fromUtf8("mActionNewProject"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/images/themes/default/mActionFileNew.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionNewProject->setIcon(icon);
        mActionOpenProject = new QAction(MainWindow);
        mActionOpenProject->setObjectName(QString::fromUtf8("mActionOpenProject"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/images/themes/default/mActionFileOpen.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionOpenProject->setIcon(icon1);
        mActionSaveProject = new QAction(MainWindow);
        mActionSaveProject->setObjectName(QString::fromUtf8("mActionSaveProject"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/images/themes/default/mActionFileSave.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSaveProject->setIcon(icon2);
        mActionSaveProjectAs = new QAction(MainWindow);
        mActionSaveProjectAs->setObjectName(QString::fromUtf8("mActionSaveProjectAs"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/images/themes/default/mActionFileSaveAs.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSaveProjectAs->setIcon(icon3);
        mActionSaveMapAsImage = new QAction(MainWindow);
        mActionSaveMapAsImage->setObjectName(QString::fromUtf8("mActionSaveMapAsImage"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/images/themes/default/mActionSaveMapAsImage.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSaveMapAsImage->setIcon(icon4);
        mActionNewPrintComposer = new QAction(MainWindow);
        mActionNewPrintComposer->setObjectName(QString::fromUtf8("mActionNewPrintComposer"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/images/themes/default/mActionNewComposer.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionNewPrintComposer->setIcon(icon5);
        mActionShowComposerManager = new QAction(MainWindow);
        mActionShowComposerManager->setObjectName(QString::fromUtf8("mActionShowComposerManager"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/images/themes/default/mActionComposerManager.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionShowComposerManager->setIcon(icon6);
        mActionExit = new QAction(MainWindow);
        mActionExit->setObjectName(QString::fromUtf8("mActionExit"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/images/themes/default/mActionFileExit.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionExit->setIcon(icon7);
        mActionExit->setMenuRole(QAction::QuitRole);
        mActionUndo = new QAction(MainWindow);
        mActionUndo->setObjectName(QString::fromUtf8("mActionUndo"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/images/themes/default/mActionUndo.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionUndo->setIcon(icon8);
        mActionRedo = new QAction(MainWindow);
        mActionRedo->setObjectName(QString::fromUtf8("mActionRedo"));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/images/themes/default/mActionRedo.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionRedo->setIcon(icon9);
        mActionCutFeatures = new QAction(MainWindow);
        mActionCutFeatures->setObjectName(QString::fromUtf8("mActionCutFeatures"));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/images/themes/default/mActionEditCut.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionCutFeatures->setIcon(icon10);
        mActionCopyFeatures = new QAction(MainWindow);
        mActionCopyFeatures->setObjectName(QString::fromUtf8("mActionCopyFeatures"));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/images/themes/default/mActionEditCopy.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionCopyFeatures->setIcon(icon11);
        mActionPasteFeatures = new QAction(MainWindow);
        mActionPasteFeatures->setObjectName(QString::fromUtf8("mActionPasteFeatures"));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/images/themes/default/mActionEditPaste.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionPasteFeatures->setIcon(icon12);
        mActionCapturePoint = new QAction(MainWindow);
        mActionCapturePoint->setObjectName(QString::fromUtf8("mActionCapturePoint"));
        mActionCapturePoint->setCheckable(true);
        QIcon icon13;
        icon13.addFile(QString::fromUtf8(":/images/themes/default/mActionCapturePoint.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionCapturePoint->setIcon(icon13);
        mActionCaptureLine = new QAction(MainWindow);
        mActionCaptureLine->setObjectName(QString::fromUtf8("mActionCaptureLine"));
        mActionCaptureLine->setCheckable(true);
        QIcon icon14;
        icon14.addFile(QString::fromUtf8(":/images/themes/default/mActionCaptureLine.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionCaptureLine->setIcon(icon14);
        mActionCapturePolygon = new QAction(MainWindow);
        mActionCapturePolygon->setObjectName(QString::fromUtf8("mActionCapturePolygon"));
        mActionCapturePolygon->setCheckable(true);
        QIcon icon15;
        icon15.addFile(QString::fromUtf8(":/images/themes/default/mActionCapturePolygon.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionCapturePolygon->setIcon(icon15);
        mActionMoveFeature = new QAction(MainWindow);
        mActionMoveFeature->setObjectName(QString::fromUtf8("mActionMoveFeature"));
        mActionMoveFeature->setCheckable(true);
        QIcon icon16;
        icon16.addFile(QString::fromUtf8(":/images/themes/default/mActionMoveFeature.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionMoveFeature->setIcon(icon16);
        mActionReshapeFeatures = new QAction(MainWindow);
        mActionReshapeFeatures->setObjectName(QString::fromUtf8("mActionReshapeFeatures"));
        mActionReshapeFeatures->setCheckable(true);
        QIcon icon17;
        icon17.addFile(QString::fromUtf8(":/images/themes/default/mActionReshape.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionReshapeFeatures->setIcon(icon17);
        mActionSplitFeatures = new QAction(MainWindow);
        mActionSplitFeatures->setObjectName(QString::fromUtf8("mActionSplitFeatures"));
        mActionSplitFeatures->setCheckable(true);
        QIcon icon18;
        icon18.addFile(QString::fromUtf8(":/images/themes/default/mActionSplitFeatures.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSplitFeatures->setIcon(icon18);
        mActionDeleteSelected = new QAction(MainWindow);
        mActionDeleteSelected->setObjectName(QString::fromUtf8("mActionDeleteSelected"));
        QIcon icon19;
        icon19.addFile(QString::fromUtf8(":/images/themes/default/mActionDeleteSelected.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionDeleteSelected->setIcon(icon19);
        mActionAddRing = new QAction(MainWindow);
        mActionAddRing->setObjectName(QString::fromUtf8("mActionAddRing"));
        mActionAddRing->setCheckable(true);
        QIcon icon20;
        icon20.addFile(QString::fromUtf8(":/images/themes/default/mActionAddRing.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionAddRing->setIcon(icon20);
        mActionAddIsland = new QAction(MainWindow);
        mActionAddIsland->setObjectName(QString::fromUtf8("mActionAddIsland"));
        mActionAddIsland->setCheckable(true);
        QIcon icon21;
        icon21.addFile(QString::fromUtf8(":/images/themes/default/mActionAddIsland.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionAddIsland->setIcon(icon21);
        mActionSimplifyFeature = new QAction(MainWindow);
        mActionSimplifyFeature->setObjectName(QString::fromUtf8("mActionSimplifyFeature"));
        mActionSimplifyFeature->setCheckable(true);
        QIcon icon22;
        icon22.addFile(QString::fromUtf8(":/images/themes/default/mActionSimplify.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSimplifyFeature->setIcon(icon22);
        mActionDeleteRing = new QAction(MainWindow);
        mActionDeleteRing->setObjectName(QString::fromUtf8("mActionDeleteRing"));
        mActionDeleteRing->setCheckable(true);
        QIcon icon23;
        icon23.addFile(QString::fromUtf8(":/images/themes/default/mActionDeleteRing.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionDeleteRing->setIcon(icon23);
        mActionDeletePart = new QAction(MainWindow);
        mActionDeletePart->setObjectName(QString::fromUtf8("mActionDeletePart"));
        mActionDeletePart->setCheckable(true);
        QIcon icon24;
        icon24.addFile(QString::fromUtf8(":/images/themes/default/mActionDeletePart.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionDeletePart->setIcon(icon24);
        mActionMergeFeatures = new QAction(MainWindow);
        mActionMergeFeatures->setObjectName(QString::fromUtf8("mActionMergeFeatures"));
        QIcon icon25;
        icon25.addFile(QString::fromUtf8(":/images/themes/default/mActionMergeFeatures.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionMergeFeatures->setIcon(icon25);
        mActionMergeFeatureAttributes = new QAction(MainWindow);
        mActionMergeFeatureAttributes->setObjectName(QString::fromUtf8("mActionMergeFeatureAttributes"));
        QIcon icon26;
        icon26.addFile(QString::fromUtf8(":/images/themes/default/mActionMergeFeatureAttributes.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionMergeFeatureAttributes->setIcon(icon26);
        mActionNodeTool = new QAction(MainWindow);
        mActionNodeTool->setObjectName(QString::fromUtf8("mActionNodeTool"));
        mActionNodeTool->setCheckable(true);
        QIcon icon27;
        icon27.addFile(QString::fromUtf8(":/images/themes/default/mActionNodeTool.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionNodeTool->setIcon(icon27);
        mActionRotatePointSymbols = new QAction(MainWindow);
        mActionRotatePointSymbols->setObjectName(QString::fromUtf8("mActionRotatePointSymbols"));
        mActionRotatePointSymbols->setCheckable(true);
        QIcon icon28;
        icon28.addFile(QString::fromUtf8(":/images/themes/default/mActionRotatePointSymbols.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionRotatePointSymbols->setIcon(icon28);
        mActionSnappingOptions = new QAction(MainWindow);
        mActionSnappingOptions->setObjectName(QString::fromUtf8("mActionSnappingOptions"));
        mActionPan = new QAction(MainWindow);
        mActionPan->setObjectName(QString::fromUtf8("mActionPan"));
        mActionPan->setCheckable(true);
        QIcon icon29;
        icon29.addFile(QString::fromUtf8(":/images/themes/default/mActionPan.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionPan->setIcon(icon29);
        mActionZoomIn = new QAction(MainWindow);
        mActionZoomIn->setObjectName(QString::fromUtf8("mActionZoomIn"));
        mActionZoomIn->setCheckable(true);
        QIcon icon30;
        icon30.addFile(QString::fromUtf8(":/images/themes/default/mActionZoomIn.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionZoomIn->setIcon(icon30);
        mActionZoomOut = new QAction(MainWindow);
        mActionZoomOut->setObjectName(QString::fromUtf8("mActionZoomOut"));
        mActionZoomOut->setCheckable(true);
        QIcon icon31;
        icon31.addFile(QString::fromUtf8(":/images/themes/default/mActionZoomOut.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionZoomOut->setIcon(icon31);
        mActionSelect = new QAction(MainWindow);
        mActionSelect->setObjectName(QString::fromUtf8("mActionSelect"));
        mActionSelect->setCheckable(true);
        QIcon icon32;
        icon32.addFile(QString::fromUtf8(":/images/themes/default/mActionSelect.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSelect->setIcon(icon32);
        mActionSelectRectangle = new QAction(MainWindow);
        mActionSelectRectangle->setObjectName(QString::fromUtf8("mActionSelectRectangle"));
        mActionSelectRectangle->setCheckable(true);
        QIcon icon33;
        icon33.addFile(QString::fromUtf8(":/images/themes/default/mActionSelectRectangle.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSelectRectangle->setIcon(icon33);
        mActionSelectPolygon = new QAction(MainWindow);
        mActionSelectPolygon->setObjectName(QString::fromUtf8("mActionSelectPolygon"));
        mActionSelectPolygon->setCheckable(true);
        QIcon icon34;
        icon34.addFile(QString::fromUtf8(":/images/themes/default/mActionSelectPolygon.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSelectPolygon->setIcon(icon34);
        mActionSelectFreehand = new QAction(MainWindow);
        mActionSelectFreehand->setObjectName(QString::fromUtf8("mActionSelectFreehand"));
        mActionSelectFreehand->setCheckable(true);
        QIcon icon35;
        icon35.addFile(QString::fromUtf8(":/images/themes/default/mActionSelectFreehand.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSelectFreehand->setIcon(icon35);
        mActionSelectRadius = new QAction(MainWindow);
        mActionSelectRadius->setObjectName(QString::fromUtf8("mActionSelectRadius"));
        mActionSelectRadius->setCheckable(true);
        QIcon icon36;
        icon36.addFile(QString::fromUtf8(":/images/themes/default/mActionSelectRadius.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSelectRadius->setIcon(icon36);
        mActionDeselectAll = new QAction(MainWindow);
        mActionDeselectAll->setObjectName(QString::fromUtf8("mActionDeselectAll"));
        QIcon icon37;
        icon37.addFile(QString::fromUtf8(":/images/themes/default/mActionDeselectAll.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionDeselectAll->setIcon(icon37);
        mActionIdentify = new QAction(MainWindow);
        mActionIdentify->setObjectName(QString::fromUtf8("mActionIdentify"));
        mActionIdentify->setCheckable(true);
        QIcon icon38;
        icon38.addFile(QString::fromUtf8(":/images/themes/default/mActionIdentify.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionIdentify->setIcon(icon38);
        mActionMeasure = new QAction(MainWindow);
        mActionMeasure->setObjectName(QString::fromUtf8("mActionMeasure"));
        mActionMeasure->setCheckable(true);
        QIcon icon39;
        icon39.addFile(QString::fromUtf8(":/images/themes/default/mActionMeasure.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionMeasure->setIcon(icon39);
        mActionMeasureArea = new QAction(MainWindow);
        mActionMeasureArea->setObjectName(QString::fromUtf8("mActionMeasureArea"));
        mActionMeasureArea->setCheckable(true);
        QIcon icon40;
        icon40.addFile(QString::fromUtf8(":/images/themes/default/mActionMeasureArea.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionMeasureArea->setIcon(icon40);
        mActionMeasureAngle = new QAction(MainWindow);
        mActionMeasureAngle->setObjectName(QString::fromUtf8("mActionMeasureAngle"));
        mActionMeasureAngle->setCheckable(true);
        QIcon icon41;
        icon41.addFile(QString::fromUtf8(":/images/themes/default/mActionMeasureAngle.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionMeasureAngle->setIcon(icon41);
        mActionZoomFullExtent = new QAction(MainWindow);
        mActionZoomFullExtent->setObjectName(QString::fromUtf8("mActionZoomFullExtent"));
        QIcon icon42;
        icon42.addFile(QString::fromUtf8(":/images/themes/default/mActionZoomFullExtent.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionZoomFullExtent->setIcon(icon42);
        mActionZoomToLayer = new QAction(MainWindow);
        mActionZoomToLayer->setObjectName(QString::fromUtf8("mActionZoomToLayer"));
        QIcon icon43;
        icon43.addFile(QString::fromUtf8(":/images/themes/default/mActionZoomToLayer.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionZoomToLayer->setIcon(icon43);
        mActionZoomToSelected = new QAction(MainWindow);
        mActionZoomToSelected->setObjectName(QString::fromUtf8("mActionZoomToSelected"));
        QIcon icon44;
        icon44.addFile(QString::fromUtf8(":/images/themes/default/mActionZoomToSelected.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionZoomToSelected->setIcon(icon44);
        mActionZoomLast = new QAction(MainWindow);
        mActionZoomLast->setObjectName(QString::fromUtf8("mActionZoomLast"));
        QIcon icon45;
        icon45.addFile(QString::fromUtf8(":/images/themes/default/mActionZoomLast.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionZoomLast->setIcon(icon45);
        mActionZoomNext = new QAction(MainWindow);
        mActionZoomNext->setObjectName(QString::fromUtf8("mActionZoomNext"));
        QIcon icon46;
        icon46.addFile(QString::fromUtf8(":/images/themes/default/mActionZoomNext.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionZoomNext->setIcon(icon46);
        mActionZoomActualSize = new QAction(MainWindow);
        mActionZoomActualSize->setObjectName(QString::fromUtf8("mActionZoomActualSize"));
        QIcon icon47;
        icon47.addFile(QString::fromUtf8(":/images/themes/default/mActionZoomActual.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionZoomActualSize->setIcon(icon47);
        mActionMapTips = new QAction(MainWindow);
        mActionMapTips->setObjectName(QString::fromUtf8("mActionMapTips"));
        mActionMapTips->setCheckable(true);
        QIcon icon48;
        icon48.addFile(QString::fromUtf8(":/images/themes/default/mActionMapTips.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionMapTips->setIcon(icon48);
        mActionNewBookmark = new QAction(MainWindow);
        mActionNewBookmark->setObjectName(QString::fromUtf8("mActionNewBookmark"));
        QIcon icon49;
        icon49.addFile(QString::fromUtf8(":/images/themes/default/mActionNewBookmark.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionNewBookmark->setIcon(icon49);
        mActionShowBookmarks = new QAction(MainWindow);
        mActionShowBookmarks->setObjectName(QString::fromUtf8("mActionShowBookmarks"));
        QIcon icon50;
        icon50.addFile(QString::fromUtf8(":/images/themes/default/mActionShowBookmarks.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionShowBookmarks->setIcon(icon50);
        mActionDraw = new QAction(MainWindow);
        mActionDraw->setObjectName(QString::fromUtf8("mActionDraw"));
        QIcon icon51;
        icon51.addFile(QString::fromUtf8(":/images/themes/default/mActionDraw.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionDraw->setIcon(icon51);
        mActionTextAnnotation = new QAction(MainWindow);
        mActionTextAnnotation->setObjectName(QString::fromUtf8("mActionTextAnnotation"));
        mActionTextAnnotation->setCheckable(true);
        QIcon icon52;
        icon52.addFile(QString::fromUtf8(":/images/themes/default/mActionTextAnnotation.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionTextAnnotation->setIcon(icon52);
        mActionFormAnnotation = new QAction(MainWindow);
        mActionFormAnnotation->setObjectName(QString::fromUtf8("mActionFormAnnotation"));
        mActionFormAnnotation->setCheckable(true);
        QIcon icon53;
        icon53.addFile(QString::fromUtf8(":/images/themes/default/mActionFormAnnotation.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionFormAnnotation->setIcon(icon53);
        mActionAnnotation = new QAction(MainWindow);
        mActionAnnotation->setObjectName(QString::fromUtf8("mActionAnnotation"));
        mActionAnnotation->setCheckable(true);
        QIcon icon54;
        icon54.addFile(QString::fromUtf8(":/images/themes/default/mActionAnnotation.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionAnnotation->setIcon(icon54);
        mActionLabeling = new QAction(MainWindow);
        mActionLabeling->setObjectName(QString::fromUtf8("mActionLabeling"));
        QIcon icon55;
        icon55.addFile(QString::fromUtf8(":/images/themes/default/mActionLabeling.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionLabeling->setIcon(icon55);
        mActionNewVectorLayer = new QAction(MainWindow);
        mActionNewVectorLayer->setObjectName(QString::fromUtf8("mActionNewVectorLayer"));
        QIcon icon56;
        icon56.addFile(QString::fromUtf8(":/images/themes/default/mActionNewVectorLayer.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionNewVectorLayer->setIcon(icon56);
        mActionNewSpatialiteLayer = new QAction(MainWindow);
        mActionNewSpatialiteLayer->setObjectName(QString::fromUtf8("mActionNewSpatialiteLayer"));
        mActionNewSpatialiteLayer->setIcon(icon56);
        mActionShowRasterCalculator = new QAction(MainWindow);
        mActionShowRasterCalculator->setObjectName(QString::fromUtf8("mActionShowRasterCalculator"));
        mActionAddOgrLayer = new QAction(MainWindow);
        mActionAddOgrLayer->setObjectName(QString::fromUtf8("mActionAddOgrLayer"));
        QIcon icon57;
        icon57.addFile(QString::fromUtf8(":/images/themes/default/mActionAddOgrLayer.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionAddOgrLayer->setIcon(icon57);
        mActionAddRasterLayer = new QAction(MainWindow);
        mActionAddRasterLayer->setObjectName(QString::fromUtf8("mActionAddRasterLayer"));
        QIcon icon58;
        icon58.addFile(QString::fromUtf8(":/images/themes/default/mActionAddRasterLayer.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionAddRasterLayer->setIcon(icon58);
        mActionAddPgLayer = new QAction(MainWindow);
        mActionAddPgLayer->setObjectName(QString::fromUtf8("mActionAddPgLayer"));
        QIcon icon59;
        icon59.addFile(QString::fromUtf8(":/images/themes/default/mActionAddLayer.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionAddPgLayer->setIcon(icon59);
        mActionAddSpatiaLiteLayer = new QAction(MainWindow);
        mActionAddSpatiaLiteLayer->setObjectName(QString::fromUtf8("mActionAddSpatiaLiteLayer"));
        QIcon icon60;
        icon60.addFile(QString::fromUtf8(":/images/themes/default/mActionAddSpatiaLiteLayer.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionAddSpatiaLiteLayer->setIcon(icon60);
        mActionAddWmsLayer = new QAction(MainWindow);
        mActionAddWmsLayer->setObjectName(QString::fromUtf8("mActionAddWmsLayer"));
        QIcon icon61;
        icon61.addFile(QString::fromUtf8(":/images/themes/default/mActionAddWmsLayer.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionAddWmsLayer->setIcon(icon61);
        mActionOpenTable = new QAction(MainWindow);
        mActionOpenTable->setObjectName(QString::fromUtf8("mActionOpenTable"));
        QIcon icon62;
        icon62.addFile(QString::fromUtf8(":/images/themes/default/mActionOpenTable.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionOpenTable->setIcon(icon62);
        mActionToggleEditing = new QAction(MainWindow);
        mActionToggleEditing->setObjectName(QString::fromUtf8("mActionToggleEditing"));
        mActionToggleEditing->setCheckable(true);
        QIcon icon63;
        icon63.addFile(QString::fromUtf8(":/images/themes/default/mActionToggleEditing.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionToggleEditing->setIcon(icon63);
        mActionSaveEdits = new QAction(MainWindow);
        mActionSaveEdits->setObjectName(QString::fromUtf8("mActionSaveEdits"));
        QIcon icon64;
        icon64.addFile(QString::fromUtf8(":/images/themes/default/mActionSaveEdits.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSaveEdits->setIcon(icon64);
        mActionLayerSaveAs = new QAction(MainWindow);
        mActionLayerSaveAs->setObjectName(QString::fromUtf8("mActionLayerSaveAs"));
        mActionLayerSelectionSaveAs = new QAction(MainWindow);
        mActionLayerSelectionSaveAs->setObjectName(QString::fromUtf8("mActionLayerSelectionSaveAs"));
        mActionRemoveLayer = new QAction(MainWindow);
        mActionRemoveLayer->setObjectName(QString::fromUtf8("mActionRemoveLayer"));
        QIcon icon65;
        icon65.addFile(QString::fromUtf8(":/images/themes/default/mActionRemoveLayer.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionRemoveLayer->setIcon(icon65);
        mActionSetLayerCRS = new QAction(MainWindow);
        mActionSetLayerCRS->setObjectName(QString::fromUtf8("mActionSetLayerCRS"));
        mActionSetProjectCRSFromLayer = new QAction(MainWindow);
        mActionSetProjectCRSFromLayer->setObjectName(QString::fromUtf8("mActionSetProjectCRSFromLayer"));
        mActionTileScale = new QAction(MainWindow);
        mActionTileScale->setObjectName(QString::fromUtf8("mActionTileScale"));
        mActionGpsTool = new QAction(MainWindow);
        mActionGpsTool->setObjectName(QString::fromUtf8("mActionGpsTool"));
        mActionLayerProperties = new QAction(MainWindow);
        mActionLayerProperties->setObjectName(QString::fromUtf8("mActionLayerProperties"));
        mActionLayerSubsetString = new QAction(MainWindow);
        mActionLayerSubsetString->setObjectName(QString::fromUtf8("mActionLayerSubsetString"));
        mActionAddToOverview = new QAction(MainWindow);
        mActionAddToOverview->setObjectName(QString::fromUtf8("mActionAddToOverview"));
        QIcon icon66;
        icon66.addFile(QString::fromUtf8(":/images/themes/default/mActionInOverview.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionAddToOverview->setIcon(icon66);
        mActionAddAllToOverview = new QAction(MainWindow);
        mActionAddAllToOverview->setObjectName(QString::fromUtf8("mActionAddAllToOverview"));
        QIcon icon67;
        icon67.addFile(QString::fromUtf8(":/images/themes/default/mActionAddAllToOverview.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionAddAllToOverview->setIcon(icon67);
        mActionRemoveAllFromOverview = new QAction(MainWindow);
        mActionRemoveAllFromOverview->setObjectName(QString::fromUtf8("mActionRemoveAllFromOverview"));
        QIcon icon68;
        icon68.addFile(QString::fromUtf8(":/images/themes/default/mActionRemoveAllFromOverview.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionRemoveAllFromOverview->setIcon(icon68);
        mActionShowAllLayers = new QAction(MainWindow);
        mActionShowAllLayers->setObjectName(QString::fromUtf8("mActionShowAllLayers"));
        QIcon icon69;
        icon69.addFile(QString::fromUtf8(":/images/themes/default/mActionShowAllLayers.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionShowAllLayers->setIcon(icon69);
        mActionHideAllLayers = new QAction(MainWindow);
        mActionHideAllLayers->setObjectName(QString::fromUtf8("mActionHideAllLayers"));
        QIcon icon70;
        icon70.addFile(QString::fromUtf8(":/images/themes/default/mActionHideAllLayers.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionHideAllLayers->setIcon(icon70);
        mActionManagePlugins = new QAction(MainWindow);
        mActionManagePlugins->setObjectName(QString::fromUtf8("mActionManagePlugins"));
        QIcon icon71;
        icon71.addFile(QString::fromUtf8(":/images/themes/default/mActionShowPluginManager.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionManagePlugins->setIcon(icon71);
        mActionToggleFullScreen = new QAction(MainWindow);
        mActionToggleFullScreen->setObjectName(QString::fromUtf8("mActionToggleFullScreen"));
        mActionProjectProperties = new QAction(MainWindow);
        mActionProjectProperties->setObjectName(QString::fromUtf8("mActionProjectProperties"));
        QIcon icon72;
        icon72.addFile(QString::fromUtf8(":/images/themes/default/mActionProjectProperties.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionProjectProperties->setIcon(icon72);
        mActionOptions = new QAction(MainWindow);
        mActionOptions->setObjectName(QString::fromUtf8("mActionOptions"));
        QIcon icon73;
        icon73.addFile(QString::fromUtf8(":/images/themes/default/mActionOptions.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionOptions->setIcon(icon73);
        mActionOptions->setMenuRole(QAction::PreferencesRole);
        mActionCustomProjection = new QAction(MainWindow);
        mActionCustomProjection->setObjectName(QString::fromUtf8("mActionCustomProjection"));
        QIcon icon74;
        icon74.addFile(QString::fromUtf8(":/images/themes/default/mActionCustomProjection.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionCustomProjection->setIcon(icon74);
        mActionConfigureShortcuts = new QAction(MainWindow);
        mActionConfigureShortcuts->setObjectName(QString::fromUtf8("mActionConfigureShortcuts"));
        mActionConfigureShortcuts->setIcon(icon73);
        mActionLocalHistogramStretch = new QAction(MainWindow);
        mActionLocalHistogramStretch->setObjectName(QString::fromUtf8("mActionLocalHistogramStretch"));
        QIcon icon75;
        icon75.addFile(QString::fromUtf8(":/images/themes/default/mActionLocalHistogramStretch.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionLocalHistogramStretch->setIcon(icon75);
        mActionHelpContents = new QAction(MainWindow);
        mActionHelpContents->setObjectName(QString::fromUtf8("mActionHelpContents"));
        QIcon icon76;
        icon76.addFile(QString::fromUtf8(":/images/themes/default/mActionHelpContents.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionHelpContents->setIcon(icon76);
        mActionHelpAPI = new QAction(MainWindow);
        mActionHelpAPI->setObjectName(QString::fromUtf8("mActionHelpAPI"));
        mActionQgisHomePage = new QAction(MainWindow);
        mActionQgisHomePage->setObjectName(QString::fromUtf8("mActionQgisHomePage"));
        QIcon icon77;
        icon77.addFile(QString::fromUtf8(":/images/themes/default/mActionQgisHomePage.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionQgisHomePage->setIcon(icon77);
        mActionCheckQgisVersion = new QAction(MainWindow);
        mActionCheckQgisVersion->setObjectName(QString::fromUtf8("mActionCheckQgisVersion"));
        QIcon icon78;
        icon78.addFile(QString::fromUtf8(":/images/themes/default/mActionCheckQgisVersion.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionCheckQgisVersion->setIcon(icon78);
        mActionAbout = new QAction(MainWindow);
        mActionAbout->setObjectName(QString::fromUtf8("mActionAbout"));
        QIcon icon79;
        icon79.addFile(QString::fromUtf8(":/images/themes/default/mActionHelpAbout.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionAbout->setIcon(icon79);
        mActionAbout->setMenuRole(QAction::AboutRole);
        mActionSponsors = new QAction(MainWindow);
        mActionSponsors->setObjectName(QString::fromUtf8("mActionSponsors"));
        QIcon icon80;
        icon80.addFile(QString::fromUtf8(":/images/themes/default/mActionHelpSponsors.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionSponsors->setIcon(icon80);
        mActionMoveLabel = new QAction(MainWindow);
        mActionMoveLabel->setObjectName(QString::fromUtf8("mActionMoveLabel"));
        mActionMoveLabel->setCheckable(true);
        QIcon icon81;
        icon81.addFile(QString::fromUtf8(":/images/themes/default/mActionMoveLabel.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionMoveLabel->setIcon(icon81);
        mActionRotateLabel = new QAction(MainWindow);
        mActionRotateLabel->setObjectName(QString::fromUtf8("mActionRotateLabel"));
        mActionRotateLabel->setCheckable(true);
        QIcon icon82;
        icon82.addFile(QString::fromUtf8(":/images/themes/default/mActionRotateLabel.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionRotateLabel->setIcon(icon82);
        mActionChangeLabelProperties = new QAction(MainWindow);
        mActionChangeLabelProperties->setObjectName(QString::fromUtf8("mActionChangeLabelProperties"));
        mActionChangeLabelProperties->setCheckable(true);
        QIcon icon83;
        icon83.addFile(QString::fromUtf8(":/images/themes/default/mActionChangeLabelProperties.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionChangeLabelProperties->setIcon(icon83);
        mActionStyleManagerV2 = new QAction(MainWindow);
        mActionStyleManagerV2->setObjectName(QString::fromUtf8("mActionStyleManagerV2"));
        mActionShowPythonDialog = new QAction(MainWindow);
        mActionShowPythonDialog->setObjectName(QString::fromUtf8("mActionShowPythonDialog"));
        mActionFullHistogramStretch = new QAction(MainWindow);
        mActionFullHistogramStretch->setObjectName(QString::fromUtf8("mActionFullHistogramStretch"));
        QIcon icon84;
        icon84.addFile(QString::fromUtf8(":/images/themes/default/mActionFullHistogramStretch.png"), QSize(), QIcon::Normal, QIcon::Off);
        mActionFullHistogramStretch->setIcon(icon84);
        mActionAddLayerSeparator = new QAction(MainWindow);
        mActionAddLayerSeparator->setObjectName(QString::fromUtf8("mActionAddLayerSeparator"));
        mActionAddLayerSeparator->setText(QString::fromUtf8("More Add Layer actions here"));
        mActionAddLayerSeparator->setIconText(QString::fromUtf8("More Add Layer actions here"));
#ifndef QT_NO_TOOLTIP
        mActionAddLayerSeparator->setToolTip(QString::fromUtf8("More Add Layer actions here"));
#endif // QT_NO_TOOLTIP
        mActionAddLayerSeparator->setVisible(false);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1054, 27));
        mEditMenu = new QMenu(menubar);
        mEditMenu->setObjectName(QString::fromUtf8("mEditMenu"));
        mFileMenu = new QMenu(menubar);
        mFileMenu->setObjectName(QString::fromUtf8("mFileMenu"));
        mRecentProjectsMenu = new QMenu(mFileMenu);
        mRecentProjectsMenu->setObjectName(QString::fromUtf8("mRecentProjectsMenu"));
        mPrintComposersMenu = new QMenu(mFileMenu);
        mPrintComposersMenu->setObjectName(QString::fromUtf8("mPrintComposersMenu"));
        mViewMenu = new QMenu(menubar);
        mViewMenu->setObjectName(QString::fromUtf8("mViewMenu"));
        menuSelect = new QMenu(mViewMenu);
        menuSelect->setObjectName(QString::fromUtf8("menuSelect"));
        menuMeasure = new QMenu(mViewMenu);
        menuMeasure->setObjectName(QString::fromUtf8("menuMeasure"));
        mLayerMenu = new QMenu(menubar);
        mLayerMenu->setObjectName(QString::fromUtf8("mLayerMenu"));
        menuNew = new QMenu(mLayerMenu);
        menuNew->setObjectName(QString::fromUtf8("menuNew"));
        mSettingsMenu = new QMenu(menubar);
        mSettingsMenu->setObjectName(QString::fromUtf8("mSettingsMenu"));
        mPluginMenu = new QMenu(menubar);
        mPluginMenu->setObjectName(QString::fromUtf8("mPluginMenu"));
        mRasterMenu = new QMenu(menubar);
        mRasterMenu->setObjectName(QString::fromUtf8("mRasterMenu"));
        mHelpMenu = new QMenu(menubar);
        mHelpMenu->setObjectName(QString::fromUtf8("mHelpMenu"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);
        mFileToolBar = new QToolBar(MainWindow);
        mFileToolBar->setObjectName(QString::fromUtf8("mFileToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mFileToolBar);
        mLayerToolBar = new QToolBar(MainWindow);
        mLayerToolBar->setObjectName(QString::fromUtf8("mLayerToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mLayerToolBar);
        mDigitizeToolBar = new QToolBar(MainWindow);
        mDigitizeToolBar->setObjectName(QString::fromUtf8("mDigitizeToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mDigitizeToolBar);
        MainWindow->insertToolBarBreak(mDigitizeToolBar);
        mAdvancedDigitizeToolBar = new QToolBar(MainWindow);
        mAdvancedDigitizeToolBar->setObjectName(QString::fromUtf8("mAdvancedDigitizeToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mAdvancedDigitizeToolBar);
        mMapNavToolBar = new QToolBar(MainWindow);
        mMapNavToolBar->setObjectName(QString::fromUtf8("mMapNavToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mMapNavToolBar);
        mAttributesToolBar = new QToolBar(MainWindow);
        mAttributesToolBar->setObjectName(QString::fromUtf8("mAttributesToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mAttributesToolBar);
        MainWindow->insertToolBarBreak(mAttributesToolBar);
        mPluginToolBar = new QToolBar(MainWindow);
        mPluginToolBar->setObjectName(QString::fromUtf8("mPluginToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mPluginToolBar);
        mHelpToolBar = new QToolBar(MainWindow);
        mHelpToolBar->setObjectName(QString::fromUtf8("mHelpToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mHelpToolBar);
        mRasterToolBar = new QToolBar(MainWindow);
        mRasterToolBar->setObjectName(QString::fromUtf8("mRasterToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mRasterToolBar);
        mLabelToolBar = new QToolBar(MainWindow);
        mLabelToolBar->setObjectName(QString::fromUtf8("mLabelToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mLabelToolBar);

        menubar->addAction(mFileMenu->menuAction());
        menubar->addAction(mEditMenu->menuAction());
        menubar->addAction(mViewMenu->menuAction());
        menubar->addAction(mLayerMenu->menuAction());
        menubar->addAction(mSettingsMenu->menuAction());
        menubar->addAction(mPluginMenu->menuAction());
        menubar->addAction(mRasterMenu->menuAction());
        menubar->addAction(mHelpMenu->menuAction());
        mEditMenu->addAction(mActionUndo);
        mEditMenu->addAction(mActionRedo);
        mEditMenu->addSeparator();
        mEditMenu->addAction(mActionCutFeatures);
        mEditMenu->addAction(mActionCopyFeatures);
        mEditMenu->addAction(mActionPasteFeatures);
        mEditMenu->addSeparator();
        mEditMenu->addAction(mActionCapturePoint);
        mEditMenu->addAction(mActionCaptureLine);
        mEditMenu->addAction(mActionCapturePolygon);
        mEditMenu->addAction(mActionMoveFeature);
        mEditMenu->addAction(mActionDeleteSelected);
        mEditMenu->addSeparator();
        mEditMenu->addAction(mActionSimplifyFeature);
        mEditMenu->addAction(mActionAddRing);
        mEditMenu->addAction(mActionAddIsland);
        mEditMenu->addAction(mActionDeleteRing);
        mEditMenu->addAction(mActionDeletePart);
        mEditMenu->addAction(mActionReshapeFeatures);
        mEditMenu->addAction(mActionSplitFeatures);
        mEditMenu->addAction(mActionMergeFeatures);
        mEditMenu->addAction(mActionMergeFeatureAttributes);
        mEditMenu->addAction(mActionNodeTool);
        mEditMenu->addAction(mActionRotatePointSymbols);
        mFileMenu->addAction(mActionNewProject);
        mFileMenu->addAction(mActionOpenProject);
        mFileMenu->addSeparator();
        mFileMenu->addAction(mRecentProjectsMenu->menuAction());
        mFileMenu->addAction(mActionSaveProject);
        mFileMenu->addAction(mActionSaveProjectAs);
        mFileMenu->addAction(mActionSaveMapAsImage);
        mFileMenu->addSeparator();
        mFileMenu->addAction(mActionNewPrintComposer);
        mFileMenu->addAction(mActionShowComposerManager);
        mFileMenu->addAction(mPrintComposersMenu->menuAction());
        mFileMenu->addSeparator();
        mFileMenu->addAction(mActionExit);
        mViewMenu->addAction(mActionPan);
        mViewMenu->addAction(mActionZoomIn);
        mViewMenu->addAction(mActionZoomOut);
        mViewMenu->addSeparator();
        mViewMenu->addAction(menuSelect->menuAction());
        mViewMenu->addAction(mActionIdentify);
        mViewMenu->addAction(menuMeasure->menuAction());
        mViewMenu->addSeparator();
        mViewMenu->addAction(mActionZoomFullExtent);
        mViewMenu->addAction(mActionZoomToLayer);
        mViewMenu->addAction(mActionZoomToSelected);
        mViewMenu->addAction(mActionZoomLast);
        mViewMenu->addAction(mActionZoomNext);
        mViewMenu->addAction(mActionZoomActualSize);
        mViewMenu->addSeparator();
        mViewMenu->addAction(mActionMapTips);
        mViewMenu->addAction(mActionNewBookmark);
        mViewMenu->addAction(mActionShowBookmarks);
        mViewMenu->addAction(mActionDraw);
        mViewMenu->addAction(mActionTileScale);
        mViewMenu->addAction(mActionGpsTool);
        menuSelect->addAction(mActionSelect);
        menuSelect->addAction(mActionSelectRectangle);
        menuSelect->addAction(mActionSelectPolygon);
        menuSelect->addAction(mActionSelectFreehand);
        menuSelect->addAction(mActionSelectRadius);
        menuSelect->addAction(mActionDeselectAll);
        menuMeasure->addAction(mActionMeasure);
        menuMeasure->addAction(mActionMeasureArea);
        menuMeasure->addAction(mActionMeasureAngle);
        mLayerMenu->addAction(menuNew->menuAction());
        mLayerMenu->addAction(mActionAddOgrLayer);
        mLayerMenu->addAction(mActionAddRasterLayer);
        mLayerMenu->addAction(mActionAddPgLayer);
        mLayerMenu->addAction(mActionAddSpatiaLiteLayer);
        mLayerMenu->addAction(mActionAddWmsLayer);
        mLayerMenu->addAction(mActionAddLayerSeparator);
        mLayerMenu->addSeparator();
        mLayerMenu->addAction(mActionOpenTable);
        mLayerMenu->addAction(mActionSaveEdits);
        mLayerMenu->addAction(mActionToggleEditing);
        mLayerMenu->addAction(mActionLayerSaveAs);
        mLayerMenu->addAction(mActionLayerSelectionSaveAs);
        mLayerMenu->addAction(mActionRemoveLayer);
        mLayerMenu->addAction(mActionSetLayerCRS);
        mLayerMenu->addAction(mActionSetProjectCRSFromLayer);
        mLayerMenu->addAction(mActionLayerProperties);
        mLayerMenu->addAction(mActionLayerSubsetString);
        mLayerMenu->addAction(mActionLabeling);
        mLayerMenu->addSeparator();
        mLayerMenu->addAction(mActionAddToOverview);
        mLayerMenu->addAction(mActionAddAllToOverview);
        mLayerMenu->addAction(mActionRemoveAllFromOverview);
        mLayerMenu->addSeparator();
        mLayerMenu->addAction(mActionShowAllLayers);
        mLayerMenu->addAction(mActionHideAllLayers);
        menuNew->addAction(mActionNewVectorLayer);
        menuNew->addAction(mActionNewSpatialiteLayer);
        mSettingsMenu->addAction(mActionProjectProperties);
        mSettingsMenu->addAction(mActionCustomProjection);
        mSettingsMenu->addAction(mActionStyleManagerV2);
        mSettingsMenu->addAction(mActionConfigureShortcuts);
        mSettingsMenu->addAction(mActionOptions);
        mSettingsMenu->addAction(mActionSnappingOptions);
        mPluginMenu->addAction(mActionManagePlugins);
        mPluginMenu->addSeparator();
        mPluginMenu->addAction(mActionShowPythonDialog);
        mRasterMenu->addAction(mActionShowRasterCalculator);
        mHelpMenu->addAction(mActionHelpContents);
        mHelpMenu->addAction(mActionHelpAPI);
        mHelpMenu->addSeparator();
        mHelpMenu->addAction(mActionQgisHomePage);
        mHelpMenu->addAction(mActionCheckQgisVersion);
        mHelpMenu->addSeparator();
        mHelpMenu->addAction(mActionAbout);
        mHelpMenu->addAction(mActionSponsors);
        mFileToolBar->addAction(mActionNewProject);
        mFileToolBar->addAction(mActionOpenProject);
        mFileToolBar->addAction(mActionSaveProject);
        mFileToolBar->addAction(mActionSaveProjectAs);
        mFileToolBar->addAction(mActionNewPrintComposer);
        mFileToolBar->addAction(mActionShowComposerManager);
        mLayerToolBar->addAction(mActionAddOgrLayer);
        mLayerToolBar->addAction(mActionAddRasterLayer);
        mLayerToolBar->addAction(mActionAddPgLayer);
        mLayerToolBar->addAction(mActionAddSpatiaLiteLayer);
        mLayerToolBar->addAction(mActionAddWmsLayer);
        mLayerToolBar->addAction(mActionNewVectorLayer);
        mLayerToolBar->addAction(mActionRemoveLayer);
        mDigitizeToolBar->addAction(mActionToggleEditing);
        mDigitizeToolBar->addAction(mActionSaveEdits);
        mDigitizeToolBar->addAction(mActionCapturePoint);
        mDigitizeToolBar->addAction(mActionCaptureLine);
        mDigitizeToolBar->addAction(mActionCapturePolygon);
        mDigitizeToolBar->addAction(mActionMoveFeature);
        mDigitizeToolBar->addAction(mActionNodeTool);
        mDigitizeToolBar->addAction(mActionDeleteSelected);
        mDigitizeToolBar->addAction(mActionCutFeatures);
        mDigitizeToolBar->addAction(mActionCopyFeatures);
        mDigitizeToolBar->addAction(mActionPasteFeatures);
        mAdvancedDigitizeToolBar->addAction(mActionUndo);
        mAdvancedDigitizeToolBar->addAction(mActionRedo);
        mAdvancedDigitizeToolBar->addAction(mActionSimplifyFeature);
        mAdvancedDigitizeToolBar->addAction(mActionAddRing);
        mAdvancedDigitizeToolBar->addAction(mActionAddIsland);
        mAdvancedDigitizeToolBar->addAction(mActionDeleteRing);
        mAdvancedDigitizeToolBar->addAction(mActionDeletePart);
        mAdvancedDigitizeToolBar->addAction(mActionReshapeFeatures);
        mAdvancedDigitizeToolBar->addAction(mActionSplitFeatures);
        mAdvancedDigitizeToolBar->addAction(mActionMergeFeatures);
        mAdvancedDigitizeToolBar->addAction(mActionMergeFeatureAttributes);
        mAdvancedDigitizeToolBar->addAction(mActionRotatePointSymbols);
        mMapNavToolBar->addAction(mActionPan);
        mMapNavToolBar->addAction(mActionZoomIn);
        mMapNavToolBar->addAction(mActionZoomOut);
        mMapNavToolBar->addAction(mActionZoomActualSize);
        mMapNavToolBar->addAction(mActionZoomFullExtent);
        mMapNavToolBar->addAction(mActionZoomToSelected);
        mMapNavToolBar->addAction(mActionZoomToLayer);
        mMapNavToolBar->addAction(mActionZoomLast);
        mMapNavToolBar->addAction(mActionZoomNext);
        mMapNavToolBar->addAction(mActionDraw);
        mAttributesToolBar->addAction(mActionIdentify);
        mAttributesToolBar->addAction(mActionDeselectAll);
        mAttributesToolBar->addAction(mActionOpenTable);
        mAttributesToolBar->addAction(mActionMapTips);
        mAttributesToolBar->addAction(mActionNewBookmark);
        mAttributesToolBar->addAction(mActionShowBookmarks);
        mHelpToolBar->addAction(mActionHelpContents);
        mRasterToolBar->addAction(mActionFullHistogramStretch);
        mRasterToolBar->addAction(mActionLocalHistogramStretch);
        mLabelToolBar->addAction(mActionLabeling);
        mLabelToolBar->addAction(mActionMoveLabel);
        mLabelToolBar->addAction(mActionRotateLabel);
        mLabelToolBar->addAction(mActionChangeLabelProperties);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        mActionNewProject->setText(QApplication::translate("MainWindow", "&New Project", 0, QApplication::UnicodeUTF8));
        mActionNewProject->setShortcut(QApplication::translate("MainWindow", "Ctrl+N", 0, QApplication::UnicodeUTF8));
        mActionOpenProject->setText(QApplication::translate("MainWindow", "&Open Project...", 0, QApplication::UnicodeUTF8));
        mActionOpenProject->setShortcut(QApplication::translate("MainWindow", "Ctrl+O", 0, QApplication::UnicodeUTF8));
        mActionSaveProject->setText(QApplication::translate("MainWindow", "&Save Project", 0, QApplication::UnicodeUTF8));
        mActionSaveProject->setShortcut(QApplication::translate("MainWindow", "Ctrl+S", 0, QApplication::UnicodeUTF8));
        mActionSaveProjectAs->setText(QApplication::translate("MainWindow", "Save Project &As...", 0, QApplication::UnicodeUTF8));
        mActionSaveProjectAs->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+S", 0, QApplication::UnicodeUTF8));
        mActionSaveMapAsImage->setText(QApplication::translate("MainWindow", "Save as Image...", 0, QApplication::UnicodeUTF8));
        mActionNewPrintComposer->setText(QApplication::translate("MainWindow", "&New Print Composer", 0, QApplication::UnicodeUTF8));
        mActionNewPrintComposer->setShortcut(QApplication::translate("MainWindow", "Ctrl+P", 0, QApplication::UnicodeUTF8));
        mActionShowComposerManager->setText(QApplication::translate("MainWindow", "Composer manager...", 0, QApplication::UnicodeUTF8));
        mActionExit->setText(QApplication::translate("MainWindow", "Exit", 0, QApplication::UnicodeUTF8));
        mActionExit->setShortcut(QApplication::translate("MainWindow", "Ctrl+Q", 0, QApplication::UnicodeUTF8));
        mActionUndo->setText(QApplication::translate("MainWindow", "&Undo", 0, QApplication::UnicodeUTF8));
        mActionUndo->setShortcut(QApplication::translate("MainWindow", "Ctrl+Z", 0, QApplication::UnicodeUTF8));
        mActionRedo->setText(QApplication::translate("MainWindow", "&Redo", 0, QApplication::UnicodeUTF8));
        mActionRedo->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+Z", 0, QApplication::UnicodeUTF8));
        mActionCutFeatures->setText(QApplication::translate("MainWindow", "Cut Features", 0, QApplication::UnicodeUTF8));
        mActionCutFeatures->setShortcut(QApplication::translate("MainWindow", "Ctrl+X", 0, QApplication::UnicodeUTF8));
        mActionCopyFeatures->setText(QApplication::translate("MainWindow", "Copy Features", 0, QApplication::UnicodeUTF8));
        mActionCopyFeatures->setShortcut(QApplication::translate("MainWindow", "Ctrl+C", 0, QApplication::UnicodeUTF8));
        mActionPasteFeatures->setText(QApplication::translate("MainWindow", "Paste Features", 0, QApplication::UnicodeUTF8));
        mActionPasteFeatures->setShortcut(QApplication::translate("MainWindow", "Ctrl+V", 0, QApplication::UnicodeUTF8));
        mActionCapturePoint->setText(QApplication::translate("MainWindow", "Capture Point", 0, QApplication::UnicodeUTF8));
        mActionCapturePoint->setShortcut(QApplication::translate("MainWindow", "Ctrl+.", 0, QApplication::UnicodeUTF8));
        mActionCaptureLine->setText(QApplication::translate("MainWindow", "Capture Line", 0, QApplication::UnicodeUTF8));
        mActionCaptureLine->setShortcut(QApplication::translate("MainWindow", "Ctrl+/", 0, QApplication::UnicodeUTF8));
        mActionCapturePolygon->setText(QApplication::translate("MainWindow", "Capture Polygon", 0, QApplication::UnicodeUTF8));
        mActionCapturePolygon->setShortcut(QApplication::translate("MainWindow", "Ctrl+?", 0, QApplication::UnicodeUTF8));
        mActionMoveFeature->setText(QApplication::translate("MainWindow", "Move Feature(s)", 0, QApplication::UnicodeUTF8));
        mActionReshapeFeatures->setText(QApplication::translate("MainWindow", "Reshape Features", 0, QApplication::UnicodeUTF8));
        mActionSplitFeatures->setText(QApplication::translate("MainWindow", "Split Features", 0, QApplication::UnicodeUTF8));
        mActionDeleteSelected->setText(QApplication::translate("MainWindow", "Delete Selected", 0, QApplication::UnicodeUTF8));
        mActionAddRing->setText(QApplication::translate("MainWindow", "Add Ring", 0, QApplication::UnicodeUTF8));
        mActionAddIsland->setText(QApplication::translate("MainWindow", "Add Part", 0, QApplication::UnicodeUTF8));
        mActionSimplifyFeature->setText(QApplication::translate("MainWindow", "Simplify Feature", 0, QApplication::UnicodeUTF8));
        mActionDeleteRing->setText(QApplication::translate("MainWindow", "Delete Ring", 0, QApplication::UnicodeUTF8));
        mActionDeletePart->setText(QApplication::translate("MainWindow", "Delete Part", 0, QApplication::UnicodeUTF8));
        mActionMergeFeatures->setText(QApplication::translate("MainWindow", "Merge selected features", 0, QApplication::UnicodeUTF8));
        mActionMergeFeatureAttributes->setText(QApplication::translate("MainWindow", "Merge attributes of selected features", 0, QApplication::UnicodeUTF8));
        mActionNodeTool->setText(QApplication::translate("MainWindow", "Node Tool", 0, QApplication::UnicodeUTF8));
        mActionRotatePointSymbols->setText(QApplication::translate("MainWindow", "Rotate Point Symbols", 0, QApplication::UnicodeUTF8));
        mActionSnappingOptions->setText(QApplication::translate("MainWindow", "Snapping Options...", 0, QApplication::UnicodeUTF8));
        mActionPan->setText(QApplication::translate("MainWindow", "Pan Map", 0, QApplication::UnicodeUTF8));
        mActionZoomIn->setText(QApplication::translate("MainWindow", "Zoom In", 0, QApplication::UnicodeUTF8));
        mActionZoomIn->setShortcut(QApplication::translate("MainWindow", "Ctrl++", 0, QApplication::UnicodeUTF8));
        mActionZoomOut->setText(QApplication::translate("MainWindow", "Zoom Out", 0, QApplication::UnicodeUTF8));
        mActionZoomOut->setShortcut(QApplication::translate("MainWindow", "Ctrl+-", 0, QApplication::UnicodeUTF8));
        mActionSelect->setText(QApplication::translate("MainWindow", "Select single feature", 0, QApplication::UnicodeUTF8));
        mActionSelectRectangle->setText(QApplication::translate("MainWindow", "Select features by rectangle", 0, QApplication::UnicodeUTF8));
        mActionSelectPolygon->setText(QApplication::translate("MainWindow", "Select features by polygon", 0, QApplication::UnicodeUTF8));
        mActionSelectFreehand->setText(QApplication::translate("MainWindow", "Select features by freehand", 0, QApplication::UnicodeUTF8));
        mActionSelectRadius->setText(QApplication::translate("MainWindow", "Select features by radius", 0, QApplication::UnicodeUTF8));
        mActionDeselectAll->setText(QApplication::translate("MainWindow", "Deselect features from all layers", 0, QApplication::UnicodeUTF8));
        mActionIdentify->setText(QApplication::translate("MainWindow", "Identify Features", 0, QApplication::UnicodeUTF8));
        mActionIdentify->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+I", 0, QApplication::UnicodeUTF8));
        mActionMeasure->setText(QApplication::translate("MainWindow", "Measure Line", 0, QApplication::UnicodeUTF8));
        mActionMeasure->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+M", 0, QApplication::UnicodeUTF8));
        mActionMeasureArea->setText(QApplication::translate("MainWindow", "Measure Area", 0, QApplication::UnicodeUTF8));
        mActionMeasureArea->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+J", 0, QApplication::UnicodeUTF8));
        mActionMeasureAngle->setText(QApplication::translate("MainWindow", "Measure Angle", 0, QApplication::UnicodeUTF8));
        mActionZoomFullExtent->setText(QApplication::translate("MainWindow", "Zoom Full", 0, QApplication::UnicodeUTF8));
        mActionZoomFullExtent->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+F", 0, QApplication::UnicodeUTF8));
        mActionZoomToLayer->setText(QApplication::translate("MainWindow", "Zoom to Layer", 0, QApplication::UnicodeUTF8));
        mActionZoomToSelected->setText(QApplication::translate("MainWindow", "Zoom to Selection", 0, QApplication::UnicodeUTF8));
        mActionZoomToSelected->setShortcut(QApplication::translate("MainWindow", "Ctrl+J", 0, QApplication::UnicodeUTF8));
        mActionZoomLast->setText(QApplication::translate("MainWindow", "Zoom Last", 0, QApplication::UnicodeUTF8));
        mActionZoomNext->setText(QApplication::translate("MainWindow", "Zoom Next", 0, QApplication::UnicodeUTF8));
        mActionZoomActualSize->setText(QApplication::translate("MainWindow", "Zoom Actual Size", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        mActionZoomActualSize->setToolTip(QApplication::translate("MainWindow", "Zoom to Native Pixel Resolution", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        mActionMapTips->setText(QApplication::translate("MainWindow", "Map Tips", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_STATUSTIP
        mActionMapTips->setStatusTip(QApplication::translate("MainWindow", "Show information about a feature when the mouse is hovered over it", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_STATUSTIP
        mActionNewBookmark->setText(QApplication::translate("MainWindow", "New Bookmark...", 0, QApplication::UnicodeUTF8));
        mActionNewBookmark->setShortcut(QApplication::translate("MainWindow", "Ctrl+B", 0, QApplication::UnicodeUTF8));
        mActionShowBookmarks->setText(QApplication::translate("MainWindow", "Show Bookmarks", 0, QApplication::UnicodeUTF8));
        mActionShowBookmarks->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+B", 0, QApplication::UnicodeUTF8));
        mActionDraw->setText(QApplication::translate("MainWindow", "Refresh", 0, QApplication::UnicodeUTF8));
        mActionDraw->setShortcut(QApplication::translate("MainWindow", "Ctrl+R", 0, QApplication::UnicodeUTF8));
        mActionTextAnnotation->setText(QApplication::translate("MainWindow", "Text Annotation", 0, QApplication::UnicodeUTF8));
        mActionFormAnnotation->setText(QApplication::translate("MainWindow", "Form annotation", 0, QApplication::UnicodeUTF8));
        mActionAnnotation->setText(QApplication::translate("MainWindow", "Move Annotation", 0, QApplication::UnicodeUTF8));
        mActionLabeling->setText(QApplication::translate("MainWindow", "Labeling", 0, QApplication::UnicodeUTF8));
        mActionNewVectorLayer->setText(QApplication::translate("MainWindow", "New Shapefile Layer...", 0, QApplication::UnicodeUTF8));
        mActionNewVectorLayer->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+N", 0, QApplication::UnicodeUTF8));
        mActionNewSpatialiteLayer->setText(QApplication::translate("MainWindow", "New SpatiaLite Layer ...", 0, QApplication::UnicodeUTF8));
        mActionNewSpatialiteLayer->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+A", 0, QApplication::UnicodeUTF8));
        mActionShowRasterCalculator->setText(QApplication::translate("MainWindow", "Raster calculator ...", 0, QApplication::UnicodeUTF8));
        mActionAddOgrLayer->setText(QApplication::translate("MainWindow", "Add Vector Layer...", 0, QApplication::UnicodeUTF8));
        mActionAddOgrLayer->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+V", 0, QApplication::UnicodeUTF8));
        mActionAddRasterLayer->setText(QApplication::translate("MainWindow", "Add Raster Layer...", 0, QApplication::UnicodeUTF8));
        mActionAddRasterLayer->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+R", 0, QApplication::UnicodeUTF8));
        mActionAddPgLayer->setText(QApplication::translate("MainWindow", "Add PostGIS Layer...", 0, QApplication::UnicodeUTF8));
        mActionAddPgLayer->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+D", 0, QApplication::UnicodeUTF8));
        mActionAddSpatiaLiteLayer->setText(QApplication::translate("MainWindow", "Add SpatiaLite Layer...", 0, QApplication::UnicodeUTF8));
        mActionAddSpatiaLiteLayer->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+L", 0, QApplication::UnicodeUTF8));
        mActionAddWmsLayer->setText(QApplication::translate("MainWindow", "Add WMS Layer...", 0, QApplication::UnicodeUTF8));
        mActionAddWmsLayer->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+W", 0, QApplication::UnicodeUTF8));
        mActionOpenTable->setText(QApplication::translate("MainWindow", "Open Attribute Table", 0, QApplication::UnicodeUTF8));
        mActionToggleEditing->setText(QApplication::translate("MainWindow", "Toggle editing", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_STATUSTIP
        mActionToggleEditing->setStatusTip(QApplication::translate("MainWindow", "Toggles the editing state of the current layer", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_STATUSTIP
        mActionSaveEdits->setText(QApplication::translate("MainWindow", "Save edits", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_STATUSTIP
        mActionSaveEdits->setStatusTip(QApplication::translate("MainWindow", "Save edits to current layer, but continue editing", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_STATUSTIP
        mActionLayerSaveAs->setText(QApplication::translate("MainWindow", "Save as...", 0, QApplication::UnicodeUTF8));
        mActionLayerSelectionSaveAs->setText(QApplication::translate("MainWindow", "Save Selection as vector file...", 0, QApplication::UnicodeUTF8));
        mActionRemoveLayer->setText(QApplication::translate("MainWindow", "Remove Layer(s)", 0, QApplication::UnicodeUTF8));
        mActionRemoveLayer->setShortcut(QApplication::translate("MainWindow", "Ctrl+D", 0, QApplication::UnicodeUTF8));
        mActionSetLayerCRS->setText(QApplication::translate("MainWindow", "Set CRS of Layer(s)", 0, QApplication::UnicodeUTF8));
        mActionSetLayerCRS->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+C", 0, QApplication::UnicodeUTF8));
        mActionSetProjectCRSFromLayer->setText(QApplication::translate("MainWindow", "Set project CRS from layer", 0, QApplication::UnicodeUTF8));
        mActionTileScale->setText(QApplication::translate("MainWindow", "Tile scale slider", 0, QApplication::UnicodeUTF8));
        mActionGpsTool->setText(QApplication::translate("MainWindow", "Live GPS tracking", 0, QApplication::UnicodeUTF8));
        mActionLayerProperties->setText(QApplication::translate("MainWindow", "Properties...", 0, QApplication::UnicodeUTF8));
        mActionLayerSubsetString->setText(QApplication::translate("MainWindow", "Query...", 0, QApplication::UnicodeUTF8));
        mActionAddToOverview->setText(QApplication::translate("MainWindow", "Add to Overview", 0, QApplication::UnicodeUTF8));
        mActionAddToOverview->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+O", 0, QApplication::UnicodeUTF8));
        mActionAddAllToOverview->setText(QApplication::translate("MainWindow", "Add All to Overview", 0, QApplication::UnicodeUTF8));
        mActionRemoveAllFromOverview->setText(QApplication::translate("MainWindow", "Remove All From Overview", 0, QApplication::UnicodeUTF8));
        mActionShowAllLayers->setText(QApplication::translate("MainWindow", "Show All Layers", 0, QApplication::UnicodeUTF8));
        mActionShowAllLayers->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+U", 0, QApplication::UnicodeUTF8));
        mActionHideAllLayers->setText(QApplication::translate("MainWindow", "Hide All Layers", 0, QApplication::UnicodeUTF8));
        mActionHideAllLayers->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+H", 0, QApplication::UnicodeUTF8));
        mActionManagePlugins->setText(QApplication::translate("MainWindow", "Manage Plugins...", 0, QApplication::UnicodeUTF8));
        mActionToggleFullScreen->setText(QApplication::translate("MainWindow", "Toggle Full Screen Mode", 0, QApplication::UnicodeUTF8));
        mActionToggleFullScreen->setShortcut(QApplication::translate("MainWindow", "Ctrl+F", 0, QApplication::UnicodeUTF8));
        mActionProjectProperties->setText(QApplication::translate("MainWindow", "Project Properties...", 0, QApplication::UnicodeUTF8));
        mActionProjectProperties->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+P", 0, QApplication::UnicodeUTF8));
        mActionOptions->setText(QApplication::translate("MainWindow", "Options...", 0, QApplication::UnicodeUTF8));
        mActionCustomProjection->setText(QApplication::translate("MainWindow", "Custom CRS...", 0, QApplication::UnicodeUTF8));
        mActionConfigureShortcuts->setText(QApplication::translate("MainWindow", "Configure shortcuts...", 0, QApplication::UnicodeUTF8));
        mActionLocalHistogramStretch->setText(QApplication::translate("MainWindow", "Local Histogram Stretch", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_STATUSTIP
        mActionLocalHistogramStretch->setStatusTip(QApplication::translate("MainWindow", "Stretch histogram of active raster to view extents", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_STATUSTIP
        mActionHelpContents->setText(QApplication::translate("MainWindow", "Help Contents", 0, QApplication::UnicodeUTF8));
        mActionHelpContents->setShortcut(QApplication::translate("MainWindow", "F1", 0, QApplication::UnicodeUTF8));
        mActionHelpAPI->setText(QApplication::translate("MainWindow", "API documentation", 0, QApplication::UnicodeUTF8));
        mActionQgisHomePage->setText(QApplication::translate("MainWindow", "QGIS Home Page", 0, QApplication::UnicodeUTF8));
        mActionQgisHomePage->setShortcut(QApplication::translate("MainWindow", "Ctrl+H", 0, QApplication::UnicodeUTF8));
        mActionCheckQgisVersion->setText(QApplication::translate("MainWindow", "Check QGIS Version", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_STATUSTIP
        mActionCheckQgisVersion->setStatusTip(QApplication::translate("MainWindow", "Check if your QGIS version is up to date (requires internet access)", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_STATUSTIP
        mActionAbout->setText(QApplication::translate("MainWindow", "About", 0, QApplication::UnicodeUTF8));
        mActionSponsors->setText(QApplication::translate("MainWindow", "QGIS Sponsors", 0, QApplication::UnicodeUTF8));
        mActionMoveLabel->setText(QApplication::translate("MainWindow", "Move Label", 0, QApplication::UnicodeUTF8));
        mActionRotateLabel->setText(QApplication::translate("MainWindow", "Rotate Label", 0, QApplication::UnicodeUTF8));
        mActionChangeLabelProperties->setText(QApplication::translate("MainWindow", "Change Label", 0, QApplication::UnicodeUTF8));
        mActionStyleManagerV2->setText(QApplication::translate("MainWindow", "Style manager...", 0, QApplication::UnicodeUTF8));
        mActionShowPythonDialog->setText(QApplication::translate("MainWindow", "Python Console", 0, QApplication::UnicodeUTF8));
        mActionFullHistogramStretch->setText(QApplication::translate("MainWindow", "Full histogram stretch", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        mActionFullHistogramStretch->setToolTip(QApplication::translate("MainWindow", "Stretch histogram to full dataset", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        mEditMenu->setTitle(QApplication::translate("MainWindow", "&Edit", 0, QApplication::UnicodeUTF8));
        mFileMenu->setTitle(QApplication::translate("MainWindow", "&File", 0, QApplication::UnicodeUTF8));
        mRecentProjectsMenu->setTitle(QApplication::translate("MainWindow", "&Open Recent Projects", 0, QApplication::UnicodeUTF8));
        mPrintComposersMenu->setTitle(QApplication::translate("MainWindow", "Print Composers", 0, QApplication::UnicodeUTF8));
        mViewMenu->setTitle(QApplication::translate("MainWindow", "&View", 0, QApplication::UnicodeUTF8));
        menuSelect->setTitle(QApplication::translate("MainWindow", "Select", 0, QApplication::UnicodeUTF8));
        menuMeasure->setTitle(QApplication::translate("MainWindow", "Measure", 0, QApplication::UnicodeUTF8));
        mLayerMenu->setTitle(QApplication::translate("MainWindow", "&Layer", 0, QApplication::UnicodeUTF8));
        menuNew->setTitle(QApplication::translate("MainWindow", "New", 0, QApplication::UnicodeUTF8));
        mSettingsMenu->setTitle(QApplication::translate("MainWindow", "&Settings", 0, QApplication::UnicodeUTF8));
        mPluginMenu->setTitle(QApplication::translate("MainWindow", "&Plugins", 0, QApplication::UnicodeUTF8));
        mRasterMenu->setTitle(QApplication::translate("MainWindow", "&Raster", 0, QApplication::UnicodeUTF8));
        mHelpMenu->setTitle(QApplication::translate("MainWindow", "&Help", 0, QApplication::UnicodeUTF8));
        mFileToolBar->setWindowTitle(QApplication::translate("MainWindow", "File", 0, QApplication::UnicodeUTF8));
        mLayerToolBar->setWindowTitle(QApplication::translate("MainWindow", "Manage Layers", 0, QApplication::UnicodeUTF8));
        mDigitizeToolBar->setWindowTitle(QApplication::translate("MainWindow", "Digitizing", 0, QApplication::UnicodeUTF8));
        mAdvancedDigitizeToolBar->setWindowTitle(QApplication::translate("MainWindow", "Advanced Digitizing", 0, QApplication::UnicodeUTF8));
        mMapNavToolBar->setWindowTitle(QApplication::translate("MainWindow", "Map Navigation", 0, QApplication::UnicodeUTF8));
        mAttributesToolBar->setWindowTitle(QApplication::translate("MainWindow", "Attributes", 0, QApplication::UnicodeUTF8));
        mPluginToolBar->setWindowTitle(QApplication::translate("MainWindow", "Plugins", 0, QApplication::UnicodeUTF8));
        mHelpToolBar->setWindowTitle(QApplication::translate("MainWindow", "Help", 0, QApplication::UnicodeUTF8));
        mRasterToolBar->setWindowTitle(QApplication::translate("MainWindow", "Raster", 0, QApplication::UnicodeUTF8));
        mLabelToolBar->setWindowTitle(QApplication::translate("MainWindow", "Label", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_QGISAPP_H
